### ISSUE TITLE
RxJava 사용

### ISSUE THREAD

**Issue by JSpiner** [Mash-Up-MapC/MapC-android#14]
RxJava의 사용을 건의해봅니다!

해커톤때부터 바로 RxJava를 도입하는건 무리가 있었지만
현재 안드로이드 프로젝트에 참여중인 3명 모두 rx스터디를 듣고있기에
큰 어려움 없이 도입해 볼 수 있을것 같습니다.

상대적으로 쉬워보이는 네트워크 요청부터 rx로 바꿔보는것 어떨까요?
```java
//ApiService.java

//rx없이
@GET("/test/api")
Response<Model> getTestApi();

//rx와 함께
@GET("/test/api")
Single<Model> getTestApi();
```

**Comment by gaonK** [comment]
흠. 열심히 공부해 보겠습니다 !

**Comment by JSpiner** [comment]
api에서부터 차차 적용해보기로 구두로 논의됬습니다!
