### ISSUE TITLE
PR review/merge 절차 논의

### ISSUE THREAD

**Issue by JSpiner** [Mash-Up-MapC/MapC-android#21]
@gaonK @Jeongah-Shin 

PR을 review하고 merge하는 절차가 조큼 통일이 안된것같아 
각자가 다르게 해석하고 있는 부분을 논의해보면 좋을것같습니다!

아래부분이 통일이 필요할것 같아요 😂 

```
1. review를 몇명에게 받아야 merge가 가능할까?
2. merge는 누가 할까?
```

아래와 같은 초안을 제안해봅니다! 👍 

```
1. 우린 한팀이니까! 모두의 리뷰를 받고난 후에 merge가 가능한 상태라고 보자.
2. 모두가 approve해도 본인이 필요한 추가 수정이 발생할 수 있으니, PR을 만든사람이 merge하자.
```

이 이외에도 review/merge 절차에 관한 의견이 있다면 이 issue에서 공유 부탁드려요! 🙏

**Comment by gaonK** [comment]
오 그렇습니닷. :+1:
성민님 초안에 동의동의!

**Comment by gaonK** [comment]
생각을 해 봤는데요! 모두가 리뷰를 봐주지 않아서 늦어질 경우의 대처는 어떻게 하는 게 좋다고 생각하시나요?!

**Comment by Jeongah-Shin** [comment]
저는 일의 진행 효율을 위해 한 사람의 리뷰만으로도 merge 할 수 있도록 하되, merge는 본인이 했으면 합니다 :smile:

**Comment by JSpiner** [comment]
@gaonK 
 
> 생각을 해 봤는데요! 모두가 리뷰를 봐주지 않아서 늦어질 경우의 대처는 어떻게 하는 게 좋다고 생각하시나요?!

고려해볼만한 케이스네요.
best practice로 본것중 하나가 리뷰를 n시간 내에 하지 않으면
슬랙 / 메신저 등으로 알림을 계속 보내 remind 시키는 방법을 본 것 같아요!

하지만 저희는 그런 봇을 만들/연동할 여력이 없으니 😂 
`8시간 내에 리뷰를 해주지 않으면 카톡/슬랙 등으로 직접 리뷰요청하기!` 어떨까요?

@Jeongah-Shin 
> 저는 일의 진행 효율을 위해 한 사람의 리뷰만으로도 merge 할 수 있도록 하되, merge는 본인이 했으면 합니다 😄

효율성은 고려를 못했었네요 😭 좋은것 같습니다.

하지만 여전히 *우린 한팀이니까!* 모두의 리뷰를 염두해 둘 필요가 있을것같습니다.
위에서 나온 8시간 규칙과 더불어 
`12시간 내에 리뷰를 해주지 않으면, 1명이상의 approve만으로 merge가능` 이라는 규칙은 어떨까요?


----
정리해보면 제가 다시 제안해보는 규칙은 아래와 같습니다.
```
1. 우린 한팀이니까! 모두의 리뷰를 받고난 후에 merge가 가능한 상태라고 보자. 
    1-1. 다만 12시간내에 리뷰를 해주지 않는다면, 1명이상의 approve만으로 merge가 가능하다.
2. 모두가 approve해도 본인이 필요한 추가 수정이 발생할 수 있으니, PR을 만든사람이 merge하자.
3. PR 생성/수정 이후 8시간 내에 추가 리뷰가 달리지 않는다면 PR을 만든사람이 카톡/슬랙으로 리뷰요청하자.
4. 내가 리뷰하기 전에 merge되었더라도, PR 확인은 꼭 해보자.
```

**Comment by JSpiner** [comment]
이 내용이 정해지면 README.md에 추가하면 좋을것같네요.

**Comment by gaonK** [comment]
@JSpiner 
8시간과 12시간으로 구체적인 시간을 정한 점이 마음에 듭니다 ! 👍
README.md에 추가하는 것도 찬성입니다.

**Comment by Jeongah-Shin** [comment]
저도 좋습니당🙂 민주주의에 걸맞는 CI 환경!
엯촋 !!!
