### ISSUE TITLE
코스별 상세정보 화면의 지도에 그려질 루트 정보 질문

### ISSUE THREAD

**Issue by opklnm102** [Mash-Up-MapC/MapC-android#23]
[A코스 상세화면](https://app.zeplin.io/project/5b6bab573b0600688b8ec7d4/screen/5b7da48de5cb4c0e963623d4)에 있는 지도에 버스 노선 루트가 보이잖아요...?
google map api를 이용하는걸로 알고 있는데. 저걸 표현하기 위해서 버스 정류장 좌표만으로도 되는지 문의드려요

**Comment by gaonK** [comment]
@opklnm102 제가 안 그래도 코스 부분을 맡아서 찾아봤는데요. 
api 상에서 점과 점 사이의 경로를 표시하는 방법이 있다고 하는데, 이게 최단 거리를 찍어주는 것인지 어떤 방식으로 경로를 탐색하는 것인지 찾아보다가 이 부분을 백엔드쪽에서 논의한다고 해서 일단 maps api를 연동하고 있었습니다. 

---
그렇다면 지금 백엔드팀에서 생각하시는 방향은 버스 정류장 좌표들을 보내주시는 건가요?
저도 관련 내용들 더 찾아보도록 하겠습니다.

**Comment by opklnm102** [comment]
현재 정류장 좌표까지만 @KiWooyoung께서 고려하셔서 android client로 얼마나 자세하게 좌표를 드려야 그릴 수 있는지..!  확인이 필요해보여서 질문했어요.

android sdk의 google map api를 사용했을 때
1. 지도위에 선을 그릴때 주어진 좌표를 직선으로만 이어주는지?
2. 아니면 지도앱처럼 지도상의 최단거리로 그릴 수 있는지?

위 2가지만 확인해주시면 될듯해요

**Comment by JSpiner** [comment]
@opklnm102 @KiWooyoung 

저번에 논의 했던것처럼 2번이 되더라도 1번으로 해야할것같습니다.

안드로이드 google map sdk내에서 두 점을 경로로 이어주는 api가 있다고 하더라도
그 기준이 '최단거리' / '최소시간' / '최소비용' 등 우리가 원하는 기준과 다를 수 있고,
그 경로가 실제 버스가 이동하는 경로와 맞지 않을것같습니다.

관광버스가  '최단거리' / '최소시간' / '최소비용'등의 경로로 이동할것같지 않아요!

1번방법으로 짧은 선을 여러개 그어 경로를 표현해야할 것 같습니다

**Comment by opklnm102** [comment]
아하 알겠습니다. 그럼 1번으로 하죠

**Comment by JSpiner** [comment]
@opklnm102 
이 이슈는 close해도 될까요?

**Comment by opklnm102** [comment]
아 넵 제가 할께여
